In [1]:
import importlib
import pandas as pd
import utils

In [2]:
importlib.reload(utils)

In [3]:
df = utils.get_product_propensity_data()

df

,Customer_ID,Age,Gender,Credit_Limit,Transaction_Source_M_Count,Transaction_Source_A_Count,Transaction_Source_D_Count,Transaction_Source_V_Count,Transaction_Source_P_Count,Transaction_Source_U_Count,Avg_Transaction_Value,Customer_Segment,Purchase
0,1,52,F,131408,1,4,1,0,1,0,149.717585,0,0
1,2,55,M,23662,1,1,0,1,1,1,481.705821,2,0
2,3,47,F,71431,0,1,0,1,0,1,103.803113,2,1
3,4,19,F,116600,0,0,0,0,1,0,236.587300,0,1
4,5,54,M,131716,1,1,0,0,1,1,226.523638,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,50,M,87907,1,2,1,1,0,0,113.028996,2,0
996,997,28,M,104151,1,3,1,1,0,1,69.241890,0,0
997,998,53,F,50991,1,4,0,1,0,1,115.177624,2,0
998,999,44,F,23446,1,0,0,1,0,0,328.316036,1,0
999,1000,44,F,86429,0,4,1,1,1,1,174.366955,1,1

In [4]:
df.iloc[:,1:].to_csv("output_data/product-propensity.csv", index=False)