In [15]:
import importlib
import pandas as pd
import utils

In [16]:
importlib.reload(utils)

In [17]:
df = utils.get_product_propensity_data()

df

,Customer_ID,Age,Gender,Credit_Limit,Transaction_Source_M_Count,Transaction_Source_A_Count,Transaction_Source_D_Count,Transaction_Source_V_Count,Transaction_Source_P_Count,Transaction_Source_U_Count,Avg_Transaction_Value,Customer_Segment,Purchase
0,1,31,F,70608,1,1,0,0,0,0,94.360044,0,1
1,2,58,M,121559,0,2,0,1,0,1,150.369170,0,1
2,3,59,F,44786,1,0,1,1,1,1,133.163031,2,0
3,4,19,F,57822,0,3,0,1,0,0,432.366657,1,1
4,5,22,F,97372,1,3,0,0,0,1,487.671096,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,54,F,141424,1,1,1,1,1,0,462.340021,0,0
996,997,66,F,113109,0,2,0,1,0,0,411.394487,0,1
997,998,63,M,46678,1,0,1,0,1,1,65.557760,1,1
998,999,54,F,86027,0,3,1,1,1,0,493.140656,1,1
999,1000,64,F,110673,0,1,1,0,1,1,59.661176,1,0

In [18]:
df.iloc[:,1:].to_csv("output_data/product-propensity.csv", index=False)